### ISSUE TITLE
Introduction to Lithnet RMConfig

### ISSUE THREAD

**Issue by myFIMGithub** [lithnet/resourcemanagement-powershell#1]
I just published a VBlog on using the Lithnet RMConfig tool.

https://tlktechidentitythoughts.wordpress.com/2016/06/25/vblog-introduction-to-lithnet-rm-config/

**Comment by ryannewington** [comment]
That's brilliant Ike. Do you mind if I link to this video in the RMConfig documentation?

**Comment by ryannewington** [comment]
Some of the text seems to have been a bit over compressed and can be hard to read
![image](https://cloud.githubusercontent.com/assets/17229877/16359320/d92f50de-3b72-11e6-9740-5dc3ce4ea0a4.png)
Or was that just my internet connection?

**Comment by myFIMGithub** [comment]
Go right ahead Ryan and link. Its your excellent work and willingness to share that benefits all of us. Ike

**Comment by myFIMGithub** [comment]
I think it has to do with the encoding software ( I used MS expression for screen capture and encoding) Its very clear in the screen capture but the conversion to wma its is not so sharp. I did post all the demo files on ondrive and put the link on my blogpost. i will also put the link to get the files on the Video page. Ike

**Comment by ryannewington** [comment]
Added to wiki Configuration Management wiki pages https://github.com/lithnet/resourcemanagement-powershell/wiki/Configuration-management
