### ISSUE TITLE
Adds support for generating RMConfig files from existing resources

### ISSUE THREAD

**Issue by ryannewington** [lithnet/resourcemanagement-powershell#12]

**Comment by jakubhkak** [comment]
yes, Export-RmConfig would be great!

**Comment by jakubhkak** [comment]
I was missing this functionality, so I created a set of scripts that can transform standard MIM XML configuration dump (ExportPolicy.ps1, SyncPolicy.ps1 etc.) into XML files suitable for Lithnet Import-RmConfig. It's here: https://github.com/Predica/MIM-to-Lithnet-XML-transformer
