### ISSUE TITLE
Doc: Possible wrong Xpath in two user examples

### ISSUE THREAD

**Issue by Ruffio** [lithnet/resourcemanagement-powershell#16]
On the example page for Search-Resource (https://github.com/lithnet/resourcemanagement-powershell/wiki/Search-Resources) there are two examples regarding searching for users.

The code remarks describe users but the code writes 'Set'. Shouldn't it be /Person instead of /Set for those two examples?
![image](https://user-images.githubusercontent.com/1877612/44391956-5e5e0280-a531-11e8-89be-c52cc1a2378f.png)

**Comment by ryannewington** [comment]
Good find @Ruffio thankyou! I've fixed the wiki pages
