### ISSUE TITLE
How to create Criteria-based group using PowerShell.

### ISSUE THREAD

**Issue by amolsp777** [lithnet/resourcemanagement-powershell#17]
How to create Criteria-based group using PowerShell.
Which attributes turns on Criteria-based group.

**Comment by FredrikMelby** [comment]
You can create an criteria based group by setting these attributes upon create:
![image](https://user-images.githubusercontent.com/29274188/52260591-e2ad1200-2926-11e9-9de3-c6e7072408aa.png)

In addition you must specify a valid XPath filter in the filter attribute.

**Comment by amolsp777** [comment]
> You can create an criteria based group by setting these attributes upon create:
> ![image](https://user-images.githubusercontent.com/29274188/52260591-e2ad1200-2926-11e9-9de3-c6e7072408aa.png)
> 
> In addition you must specify a valid XPath filter in the filter attribute.

Yeah I
