### ISSUE TITLE
What is the Criteria-based group's conditions capacity?

### ISSUE THREAD

**Issue by amolsp777** [lithnet/resourcemanagement-powershell#18]
Hello, 

What is the Criteria-based group's conditions capacity?
I have 500+ 'OR' Conditions to create group and trying to create using your module but i guess it is getting failed due to over limit. 
Getting below error. Please help. 

Save-Resource : Failure Message: 
Failure Source: Other
Details: Request could not be dispatched.
Correlation ID:3950d04e-d653-435b-ae4a-e6d5e25b16ea
At C:\Amolp\MIM-CreateCriteriaGroups-CostCenters.ps1:182 char:1
+ Save-Resource $GroupModify
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Save-Resource], UnwillingToPerformException
    + FullyQualifiedErrorId : Lithnet.ResourceManagement.Client.UnwillingToPerformException,Lithnet.ResourceManagement.Automation.SaveResource

**Comment by jhbooth** [comment]
Geez, 500+ OR conditions. Seems a little extreme
 😊
I think this might be a MIM limit, not a Lithnet
limit

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by darrenjrobinson** [comment]
The Lithnet RMA library will respect FIM/MIM. 
Sounds like you need to think about what you are trying to achieve. If you have CBG's with that type of criteria you're going to have other probelms. See https://social.technet.microsoft.com/Forums/en-US/81eb2fbc-96fb-400b-94da-72fc40873e8e/is-there-a-limit-to-the-number-of-conditions-andor-subconditions-in-a-set-membership-criteria?forum=ilm2
