### ISSUE TITLE
GET request for policy

### ISSUE THREAD

**Issue by kongarasri** [lithnet/resourcemanagement-powershell#20]
**Would it be possible to expose the approvals resource via another API?**

 __[SwaggerWcfPath("Get approval requests", "Get approval requests")] 
68         [OperationContract] 
69         [WebGet(UriTemplate = "/approvals/", ResponseFormat = WebMessageFormat.Json, RequestFormat = WebMessageFormat.Json)] 
70         Stream GetApprovalRequests(); 
71 
 
72         [SwaggerWcfPath("Get approval requests", "Get approval requests")] 
73         [OperationContract] 
74         [WebGet(UriTemplate = "/approvals/{status}", ResponseFormat = WebMessageFormat.Json, RequestFormat = WebMessageFormat.Json)] 
75         Stream GetApprovalRequestsByStatus(string status); 
76 
 
77         [SwaggerWcfPath("Approve request", "Approve request")] 
78         [OperationContract] 
79         [WebInvoke(UriTemplate = "/approvals/{id}/{decision}", Method = "POST", ResponseFormat = WebMessageFormat.Json, RequestFormat = WebMessageFormat.Json)] 
80         void SetPendingApproval(string id, string decision, ApprovalReason reason);__ 

**We need to programmatically discern users based off of their approval policy.**

**Comment by ryannewington** [comment]
Hi. I'm not sure exactly what you mean. Can you elaborate or give an example of what you are trying to do?

**Comment by kongarasri** [comment]
I was trying to do a GET request for a policy, can you provide us any endpoint reference for that?

**Comment by ryannewington** [comment]
If you are using about an mpr, then you would just use the standard resources endpoint to obtain the object. Everything in FIM is a resource, even sets, mprs, schema definition etc. The only reason why approval submissions are different is because they are exposed via a different mechanism in FIM. Everything else is a resource.
