### ISSUE TITLE
Unable to add multiple members to group

### ISSUE THREAD

**Issue by FizzGiGG** [lithnet/resourcemanagement-powershell#22]
Digging through all of the documentation, wiki, the googles, etc... I am unable to find anything referencing how to add multiple members to a group.

My project involves migrating all AD security groups into MIM. We would love to be able to use the Lithnet module as it appears to be a much more simple and efficient means of doing so.

Help!! The script works great when configured to use the FIM Automation module, but we can't get Lithnet to play nice. Do you have any examples of how to write out multiple users to the group in one fell swoop?

Thanks for any assistance you can offer up.

**Comment by FizzGiGG** [comment]
Nevermind! incorrect syntax on the .Add.

**Comment by joshbgosh10592** [comment]
> Nevermind! incorrect syntax on the .Add.

I know this is a super old thread, but any chance you still have the code for this? I'm needing to create a bunch of Manually Managed groups and can't figure out how to do anything other than criteria-based...
