### ISSUE TITLE
Get All Users

### ISSUE THREAD

**Issue by ashishnt** [lithnet/resourcemanagement-powershell#23]
How to Get all Users ?
I tried $AllUsers = Search-Resources -XPath "/Person";

and only returns Attributes and no values

@{; AccountName=; AD_UserCannotChangePassword=; Address=; Assistant=; AuthNLockoutRegistrationID=Lithnet.ResourceManagement.Automation.AttributeValueArrayList; AuthNWFLockedOut=Lithnet
.ResourceManagement.Automation.AttributeValueArrayList; AuthNWFRegistered=Lithnet.ResourceManagement.Automation.AttributeValueArrayList; City=; Company=; CostCenter=; CostCenterName=; Country
=; CreatedTime=; Creator=; DeletedTime=; Department=; Description=; DetectedRulesL......................................................................................................

**Comment by ryannewington** [comment]
Hi @ashishnt,

Youll need to use the AttributesToGet parameter on the cmdlet to specify what attributes you want to return.

https://github.com/lithnet/resourcemanagement-powershell/wiki/Search-Resources

This is to make sure only the data you need is returned from the search to keep things as efficient as possible

Hope that helps
