### ISSUE TITLE
Failure searching on /Resource[ObjectType = 'RoleGroup']

### ISSUE THREAD

**Issue by Amethi** [lithnet/resourcemanagement-powershell#24]
I have two similar resource types that I want to search across.

I've tried starting off with one resource type with the intent to add more resource types later:
Search-Resources -XPath "/Resource[ObjectType = 'RoleGroup']"

But this results in a failure. The event log contains:

> Requestor: urn:uuid:7fb2b853-24f0-4498-9534-4e10589723c4
> Correlation Identifier: 54cc06a5-3d21-4365-9bff-3e7ffc2a2558
> Microsoft.ResourceManagement.WebServices.Exceptions.UnwillingToPerformException: Other ---> System.Data.SqlClient.SqlException: Incorrect syntax near ')'.
> Incorrect syntax near ','.
> Incorrect syntax near ','.
> Incorrect syntax near ','.
>    at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection)
>    at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj)
>    at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
>    at System.Data.SqlClient.SqlDataReader.ConsumeMetaData()
>    at System.Data.SqlClient.SqlDataReader.get_MetaData()
>    at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, DbAsyncResult result)
>    at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
>    at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
>    at System.Data.SqlClient.SqlCommand.ExecuteReader()
>    at Microsoft.ResourceManagement.Query.QueryProcessor.ExecuteQuery(Query query, Nullable`1 maximumTime, Boolean& endOfSequence, Boolean countResultsOnly, Int64& resultCount, Int64& executionTime)
>    at Microsoft.ResourceManagement.WebServices.RequestDispatcher.ExecutePullActionImpl(PullRequestParameter pullParameter)
>    at Microsoft.ResourceManagement.WebServices.RequestDispatcher.ExecuteEnumerateAction(RequestType request)
>    at Microsoft.ResourceManagement.WebServices.RequestDispatcher.ExecuteAction(RequestType request)
>    at Microsoft.ResourceManagement.WebServices.RequestDispatcher.ExecuteAction[ResponseBodyType](RequestType request)
>    at Microsoft.ResourceManagement.WebServices.RequestDispatcher.DispatchRequest[ResponseBodyType](RequestType request, Guid requestIdentifier, Object redispatchSingleInstanceKey, Boolean isRedispatch)
>    at Microsoft.ResourceManagement.WebServices.RequestDispatcher.DispatchRequest[ResponseBodyType](RequestType request)
>    at Microsoft.ResourceManagement.WebServices.ResourceManagementService.Enumerate(Message request)
>    --- End of inner exception stack trace ---

Any idea what's wrong?

**Comment by Amethi** [comment]
Oh so it turns out MIM doesn't let you filter on the ObjectType attribute. Wut.

**Comment by ryannewington** [comment]
Oh I didn't realise that. You can combine xpaths into a single search. Eg

'/RoleGroup or /Person'

But does mean you have to double up on the search criteria.

**Comment by Amethi** [comment]
You can't do '/RoleGroup or /Person'
But you can do '/*[ObjectType = "RoleGroup" or ObjectType = "Person"]

Thanks!

**Comment by ryannewington** [comment]
Weird!!
