### ISSUE TITLE
Not possible to manage Localized names in schema objects

### ISSUE THREAD

**Issue by KentNordstrom** [lithnet/resourcemanagement-powershell#26]
I have several customers here in Sweden that have applied the Swedish Language Pack.
When using LithnetRMA to add Schema resources like AttributeTypeDescription there is no way (at least that I have found) to also manage the Localized values of the DisplayName and Description.

**Comment by ryannewington** [comment]
Hi Kent,

Does this work?

```powershell
$obj = Get-Resource AttributeTypeDescription Name DisplayName -Locale it-IT
$obj.DisplayName = "Nome visualizzato"
Save-Resource $obj -Locale it-IT
```

**Comment by KentNordstrom** [comment]
Oh my good... sorry... totally forgot about the -Locale parameter ;-)

**Comment by ryannewington** [comment]
Add another beer to your tab
