### ISSUE TITLE
PowerShell Core Support Request

### ISSUE THREAD

**Issue by chenrylee** [lithnet/resourcemanagement-powershell#27]
Thank you for the great work, and now PowerShell Core is growing, is there a plan that this module supports PowerShell Core 7.x?

**Comment by ryannewington** [comment]
Hi @chenrylee 

Poweshell core requires dot net core, which doesn't have support for the type of Web service endpoint that the FIM service exposes. So unfortunately unless Microsoft update the FIM service endpoint to support dotnet core, we are stuck in the dotnet framework and therefore old power shell world.

Ryan

**Comment by chenrylee** [comment]
Hi @ryannewington 
Thank you for the reply, I understood~ so let's wait for the .net support. Or maybe there's a totally new system for resource management. 😄
