### ISSUE TITLE
exception after powershell 7.1 install

### ISSUE THREAD

**Issue by Keldandorin** [lithnet/resourcemanagement-powershell#29]
Hi,
I get

Get-Resource: The type initializer for 'Lithnet.ResourceManagement.Client.ResourceManagementClient' threw an exception.

when running

Get-Resource -ObjectType Person -AttributeName AccountName -AttributeValue 'hakakn001_test'

After installing powershell 7.1. Bug or expected behavior?

Thx 
//Håkan

PS module version is 1.0.6911.20437

**Comment by ryannewington** [comment]
@Keldandorin 

You will not be able to use this model with the PowerShell Core family. 

PowerShell Core is based on .net core, which doesn't have support for the specific protocol needed to talk to the fim service web service endpoint. So we are stuck on .net framework and versions of PowerShell based on that.

Microsoft have no plans on adding the missing support to .net core, and no plans to change the way we talk to the fim service.

Ryan
