### ISSUE TITLE
PowerShell Core (7.X) Support

### ISSUE THREAD

**Issue by RobinBeismann** [lithnet/resourcemanagement-powershell#30]
Hello,

first of, thanks for the awesome module, I've been using it a lot in the last years.
I'm now trying to use it with [Pode](https://github.com/Badgerati/Pode) using IIS and Kerberos Constrained Delegation but it seems like it isn't compatible.

When trying to do a Search-Ressource, I'm getting the following error. This works fine on PowerShell 5.1 through. I've loaded the module with `-SkipEditionCheck` to avoid Compat Mode - with Compat Mode it seems to load atleast.

Would it be possible to get PS 7 Support?
```

     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | The type initializer for 'Lithnet.ResourceManagement.Client.ResourceManagementClient' threw an exception.

```

**Comment by RobinBeismann** [comment]
This would also address #29

**Comment by ryannewington** [comment]
Sadly, this isn't possible. PowerShell Core is based on .net core, which doesn't have support for the specific protocol needed to talk to the fim service web service endpoint. So we are stuck on .net framework and versions of PowerShell based on that.

Microsoft have no plans on adding the missing support to .net core, and no plans to change the way we talk to the fim service.

**Comment by RobinBeismann** [comment]
I see, makes sense. :/
Instead I'll fallback to your REST Webservice, I prefer using Webservices over Modules anyway.

Thanks for the extended response tho!

**Comment by ryannewington** [comment]
I'm keeping an eye on the situation, and if anything changes, I will update the module. The code itself has been ported, it just doesn't work without the underlying support from .net core.
