### ISSUE TITLE
Not able to get Owner details using Get-resource command.

### ISSUE THREAD

**Issue by mimuser50** [lithnet/resourcemanagement-powershell#32]
Hi I am running Powershell version 5.0 and while running the command 
$obj = Get-Resource -ObjectType Person -AttributeName AccountName -AttributeValue ******

not getting Owner details its showing blank.
Please assist.

**Comment by ryannewington** [comment]
Are you getting other values?

The only cause of empty attributes being returned is when the calling account doesn't have access to read that attribute (or the attribute doesn't have a value)

**Comment by mimuser50** [comment]
Hi Ryan,

Thanks for the reply. Yes, i am able to get other values. I have another environment with PS version 4.0 where same script is generating Owner details. Till last month same script was working using same rights but now Owner details are not displaying.

Thanks.

**Comment by ryannewington** [comment]
So, same account, same mim instance, same query. The only difference is the PowerShell version?

If you upgrade the PS4 machine to PS5 does it stop working? Or the other way around, if you downgrade from PS5 to 4 does it start working?

We use PowerShell 5 exclusively and don't have this issue, so I just want to rule in or out the PowerShell version factor here.
