### ISSUE TITLE
Error when I try to Set-ResourceManagementClient

### ISSUE THREAD

**Issue by IoannisPant** [lithnet/resourcemanagement-powershell#33]
Set-ResourceManagementClient -BaseAddress http://10.0.128.26:82
Set-ResourceManagementClient : The HTTP request is unauthorized with client authentication scheme 'Anonymous'. The auth
entication header received from the server was 'Negotiate,NTLM'.
At line:1 char:1
+ Set-ResourceManagementClient -BaseAddress http://10.0.128.26:82
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-ResourceManagementClient], MessageSecurityException
    + FullyQualifiedErrorId : System.ServiceModel.Security.MessageSecurityException,Lithnet.ResourceManagement.Automat
   ion.SetResourceManagementClient

**Comment by ryannewington** [comment]
@alfieDeadpool The FIM Service usually listens on port 5725. I think you might be hitting another endpoint that is not FIM Service there.
