### ISSUE TITLE
Context for running the PS

### ISSUE THREAD

**Issue by fieldtester** [lithnet/resourcemanagement-powershell#35]
Works fine if you are an Administrator but you cannot run in the context of the FIM Service? So if you are trying to run in a MIMWAL PowerShell workflow you will have to use a different actor?

```
WAL (2.19.0112.0): 05/04/2021 10:55:27.7596: RunPowerShellScript : RunScript: PowerShell script execution resulted in 22 error(s):\nSearch-Resources : Failure Message: 
Failure Source: IdentityIsNotFound

Details: The requestor's identity was not found.

```

**Comment by ryannewington** [comment]
That error means the mim service couldn't match the requester to a user in the mim service db. Is the mim service account known to the mim service itself?
