### ISSUE TITLE
Is this module compatible with PowerShell 7?

### ISSUE THREAD

**Issue by WillyMoselhy** [lithnet/resourcemanagement-powershell#37]
I tried running `Set-ResourceManagementClient` on PowerShell 7 but got error  `The type initializer for Lithnet.ResourceManagement.Client.ResourceManagementClient' threw an exception.` 

Is it compatible PoSH7? any plans to make it happen?

**Comment by ryannewington** [comment]
Hi @WillyMoselhy

Unfortunately, it's not possible at this stage. PS core is based on dot net core, which lacks the specific WCF support that is needed to talk to the MIM service API. Apparently there are no plans to port the missing capability to dotnet core, so we are stuck with using .net framework and PowerShell classic.

I've made several attempts to work around the missing capability, but it doesn't seem possible.

The only workaround if you must use PowerShell Core, is to deploy the Lithet REST API for MIM and use PS cores invoke web request functions against that.

Ryan
