### ISSUE TITLE
Getting Member of Set Using Search-Resource But It Giving Wrong Members Not Real Time Members

### ISSUE THREAD

**Issue by mishras90** [lithnet/resourcemanagement-powershell#39]
We have created a set on MIM portal and trying to get the member of that set using power script using Search-Resource lithnet RMA command but getting wrong data count also command is giving wrong users (may be older using which were part of set previously)

We are using date filed also in the set criterial to get using whose date is today's date, and if try to fetch the record without any date criterial then search-resource is giving correct result although this issue we started getting since last few days previously it was working properly.

Can you please help us to figure out what could be the root cause OR if it is existing issue with temporal set then what is fix for it ?

**Comment by mrmueller** [comment]
Maybe it is related to[https://tlktechidentitythoughts.wordpress.com/2017/03/15/mim-2016fim-2010-r2-using-datetime-field-as-criteria-set-conditions/]( https://tlktechidentitythoughts.wordpress.com/2017/03/15/mim-2016fim-2010-r2-using-datetime-field-as-criteria-set-conditions/)

Run the temporal events sql job on the sql server to test. Not sure of the job's name right now but you should be able to find it.
