### ISSUE TITLE
Set-ResourceManagementClient fails when using PowerShell 7.4+

### ISSUE THREAD

**Issue by premstad** [lithnet/resourcemanagement-powershell#40]
When using LithnetRMA version 1.0.6911.20437 with PowerShell 7.4.1, the 'Set-ResourceManagementClient' command throws the following error:

Set-ResourceManagementClient: The type initializer for 'Lithnet.ResourceManagement.Client.ResourceManagementClient' threw an exception.

The command runs successfully from the built-in Windows PowerShell, version 5.1.14393.6343.  The server is running Windows Server 2016.  We are attempting to move processes over to utilizing PowerShell 7 wherever possible as some other tools now require the use of PowerShell 7.

**Comment by ryannewington** [comment]
@premstad unfortunately the current version works on .NET Framework only, therefore requires Windows PowerShell to work.

Microsoft have not provided updated libraries that allow new .NET (core) to talk to the MIM service. Therefore, for now, we are unable to use PowerShell versions based on .NET core (6+)

We're experimenting with some novel ways to bring PSCore support in the future, but nothing available at this stage.
