### ISSUE TITLE
Missing Get-ApprovalRequest

### ISSUE THREAD

**Issue by Keldandorin** [lithnet/resourcemanagement-powershell#5]
Get- ApprovalRequest is gone in version 6088.
Intended or a bugg?

**Comment by Keldandorin** [comment]
PS C:\Windows\system32> get-command -Module LithnetRmA

CommandType     Name                                               Version    Source                                                                                                     
-----------     ----                                               -------    ------                                                                                                     
Cmdlet          Get-Resource                                       1.0.6088   lithnetrma                                                                                                 
Cmdlet          Get-ResourceCount                                  1.0.6088   lithnetrma                                                                                                 
Cmdlet          Import-RMConfig                                    1.0.6088   lithnetrma                                                                                                 
Cmdlet          New-Resource                                       1.0.6088   lithnetrma                                                                                                 
Cmdlet          New-ResourceUpdateTemplate                         1.0.6088   lithnetrma                                                                                                 
Cmdlet          New-XPathExpression                                1.0.6088   lithnetrma                                                                                                 
Cmdlet          New-XPathQuery                                     1.0.6088   lithnetrma                                                                                                 
Cmdlet          New-XPathQueryGroup                                1.0.6088   lithnetrma                                                                                                 
Cmdlet          Remove-Resource                                    1.0.6088   lithnetrma                                                                                                 
Cmdlet          Save-Resource                                      1.0.6088   lithnetrma                                                                                                 
Cmdlet          Search-Resources                                   1.0.6088   lithnetrma                                                                                                 
Cmdlet          Search-ResourcesPaged                              1.0.6088   lithnetrma                                                                                                 
Cmdlet          Set-ResourceManagementClient                 1.0.6088  ithnetrma                                                                                                 
Cmdlet          Update-ResourceManagementClientSchema              1.0.6088   lithnetrma

**Comment by ryannewington** [comment]
Hi @Keldandorin 

I just downloaded from github and installed on a fresh machine and the cmdlet is available

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\rnewing> ipmo lithnetrma
PS C:\Users\rnewing> get-command -module lithnetrma

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Get-ApprovalRequest                                1.0.6088   lithnetrma
Cmdlet          Get-Resource                                       1.0.6088   lithnetrma
Cmdlet          Get-ResourceCount                                  1.0.6088   lithnetrma
Cmdlet          Import-RMConfig                                    1.0.6088   lithnetrma
Cmdlet          New-Resource                                       1.0.6088   lithnetrma
Cmdlet          New-ResourceUpdateTemplate                         1.0.6088   lithnetrma
Cmdlet          New-XPathExpression                                1.0.6088   lithnetrma
Cmdlet          New-XPathQuery                                     1.0.6088   lithnetrma
Cmdlet          New-XPathQueryGroup                                1.0.6088   lithnetrma
Cmdlet          Remove-Resource                                    1.0.6088   lithnetrma
Cmdlet          Save-Resource                                      1.0.6088   lithnetrma
Cmdlet          Search-Resources                                   1.0.6088   lithnetrma
Cmdlet          Search-ResourcesPaged                              1.0.6088   lithnetrma
Cmdlet          Set-PendingApprovalRequest                         1.0.6088   lithnetrma
Cmdlet          Set-ResourceManagementClient                       1.0.6088   lithnetrma
Cmdlet          Update-ResourceManagementClientSchema              1.0.6088   lithnetrma

```

Perhaps uninstall and reinstall the module?

**Comment by Keldandorin** [comment]
Strange will do that thx
