### ISSUE TITLE
Some Remove-Resource cmdlet examples are incorrect

### ISSUE THREAD

**Issue by Identitry** [lithnet/resourcemanagement-powershell#6]
Hi!
The use of "Search-Resource" cmdlet in the Remove-Resource cmdlet examples is incorrect and should of course be "Search-Resources", also the piping of Remove-Resource to Search-Resource seems incorrect...

# Delete all email templates one at a time
**Remove-Resource | **Search-Resource** -Xpath "/EmailTemplate"**

# Delete all email templates as a composite operation
$resources = **Search-Resource** -Xpath "/EmailTemplate"
Remove-Resource $resources

**Comment by ryannewington** [comment]
Thanks @Identitry, that was really wrong! Good pickup! I've updated the doco now.
