### ISSUE TITLE
Feature Request: New-Resource cmdlet for complete resource (Add-Resource?)

### ISSUE THREAD

**Issue by Identitry** [lithnet/resourcemanagement-powershell#7]
Hi Ryan!
I would love the possibility to create a new resource from a complete in-memory resource or maybe update an existing one with the same value for example for displayname, pretty much as the OOB configuration migration works.

The idea here is to move configuration in a simple manner, easier than the RM Config and instead use for example Cli-xml... I export resources from one environment to Cli-xml, move the file to another environment, import it and then simply import it to the new environment using this new cmdlet.

I do know there are some attributes that shouldn't be exported like ObjectID and ComputedMember etc. but that should be fairly simple to filter out.

What do you think?

**Comment by ryannewington** [comment]
Hi Henrick,

It is certainly possible. Are you thinking like an export-resource and import-resource cmdlet to import/export individual resources?

Or something duplicating the functionality of FIMAutomation? How would it differ from what you can do with that module?

Some other ideas from reading your post could be a Clone-Resource, which would use an existing resource as a template for a new resource? Or an Add-Resource cmdlet that takes a hashtable of attribute/value pairs and saves directly to the FIM service.

Let me know your thoughts, and if you have specific examples for me to build the functionality around.

Cheers

Ryan

**Comment by Identitry** [comment]
Not Add-Resource, I'm thinking more about extending New-Resource to act as a Clone-Resource that takes a complete in-memory resource as argument that could have been exported using Get-Resource from a different environment but not saving it directly to FIM Service. Think New-Resource but instead of just taking the object type of the returned resource it takes a complete resource and determines object type from the source resource. Not having a FIM/MIM environment available right now and unsure about what type Get-Resource returns but if it's a hashtable then that would be exactly what this should take as argument to populate attributes of the then returned resource.

Example for migrating configuration (one command/line for clarity):
```powershell
# Dev/Test Environment:
$Set = Get-Resource -ObjectType "Set" -AttributeName "DisplayName" -AttributeValue "Some Set"
$Set | Export-CliXml - Path "C:\Set.xml"

# Prod Environment:
$Set = Import-CliXml -Path "C:\Set.xml"
$NewSet = $Set | New-Resource 
$NewSet | Save-Resource
```

This extended New-Resource could together with Get-Resource act as a "Clone-Resource"...
```powershell
$Set = Get-Resource -ObjectType "Set" -AttributeName "DisplayName" -AttributeValue "Some Set"
$ClonedSet = $Set | New-Resource
$ClonedSet.DisplayName = "Cloned Set"
$ClonedSet | Save-Resource
```

It would also be great if it would be possible to do a join/match like FIM Automations Join-FIMConfig cmdlet with for example a JoinAttribute parameter. My idea here is that the input resource would be the source and the Add-Resource cmdlet would use Get-Resource under the hood to find the matching target resource that if found would be returned and updated instead of added (ObjectID would be kept from target resource).
Example:
```powershell
# Dev/Test Environment:
$SourceSet = Get-Resource -ObjectType "Set" -AttributeName "DisplayName" -AttributeValue "Some Set"
$SourceSet | Export-CliXml - Path "C:\Set.xml"`

# Prod Environment:
$SourceSet = Import-CliXml -Path "C:\Set.xml"
$TargetSet = $SourceSet | New-Resource -JoinAttribute "DisplayName"
#Under the hood 1: $TargetSet = Get-Resource -ObjectType $SourceSet.ObjectType -AttributeName $JoinAttribute -AttributeValue $SourceSet.$JoinAttribute
#Under the hood 2(simplified): $TargetSet = $SourceSet
#Under the hood 3: Return $TargetSet
$TargetSet | Save-Resource
```
