### ISSUE TITLE
Unable to save dynamic group if filter contains a comma or forward slash...

### ISSUE THREAD

**Issue by salimassaf** [lithnet/resourcemanagement-powershell#8]
[Filter.txt](https://github.com/lithnet/resourcemanagement-powershell/files/1102648/Filter.txt)

I am attempting to create a dynamic distribution group, which contains an xpath filter as per the attachment.    To the best of my knowledge this is a valid filter, but when you run Save-Resouces, you encounter an error "ValueViolatesRegularExpression".  This seems to occur when the property value contains a forward slash or comma.

**Comment by ryannewington** [comment]
Hi @salimassaf 

That is an error coming from the MIM service itself (not from the powershell module) saying that the value is not allowed. You will see the same error trying to create that filter in the MIM portal.

The OfficeLocation attribute must have a validation regex on it in the MIM schema preventing the use of that value.

Hope that helps

Ryan

**Comment by salimassaf** [comment]
Hi Ryan,
I appreciate the quick response.  Would you mind doing a test on your system - just to be 100% certain?  
  -I confirmed I can create the dynamic groups manually through the portal without any issues, therefore I don't think it would be a regex issue.
  -I still checked to confirm there is no validation regex on the schema attribute or binding. 
  -I tried a few different attributes other than OfficeLocation with the same result.  
  -I imported a working filter from an existing dynamic group that I created,  and received the same results.  This was to confirm that there are no issues with the filter itself.

Worst case scenario, I might try it with a different PowerShell module to see if I get the same results.

Thanks,

Salim Assaf

**Comment by ryannewington** [comment]
Hi Salim,

I'm 100% sure that its the FIM Service rejecting the update because that exception code you see can only come from the FIM Service. The PowerShell module does not generate it. If you check the event log on your FIM service server, you should see more detail of the fault and what attribute is causing it.

I'm happy to run it on my side, if you can provide the entire create command you are using 

Ryan

**Comment by salimassaf** [comment]
Your 100% right!  I was trying to update the account name with a slash or comma, which I somehow managed to completely overlook.  I appreciate the help and thanks for all the wonderful work you have done so far on this!
